name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh                      # Ensure .ssh directory exists
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa  # Decode the private key from secrets
          chmod 600 ~/.ssh/id_rsa              # Set appropriate permissions for the private key

      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts               # Debugging: Output known_hosts for verification

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-basic-auth-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-basic-auth-service:latest

      - name: Deploy to Remote Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-basic-auth-service:latest
          docker stop nodejs-service || true
          docker rm nodejs-service || true
          docker run -d --name nodejs-service -p 3000:3000 --env-file /path/to/your/.env ${{ secrets.DOCKER_USERNAME }}/nodejs-basic-auth-service:latest
          EOF
